version: 0.1

log:
  accesslog:
    disabled: false
  level: debug
  formatter: text
  fields:
    service: registry

storage:
  filesystem:
    rootdirectory: /var/lib/registry
    maxthreads: 100
  delete:
    enabled: true

http:
  addr: ":5000"
  net: tcp
  tls:
    certificate: /certs/cert.crt
    key: /certs/cert.key
      # - lientcas:
    # - /certs/cert.crt
auth:
  token:
    realm: https://registry.local:8443/api/v1/registry/auth  # <- external ip or host accessible for clients from outside of container
    service: container_registry
    issuer: registry_token_issuer
    rootcertbundle: /certs/cert.crt

notifications:
  events:
    includereferences: true
  endpoints:
    - name: ra-listener
      disabled: false
      url: https://registry-admin/api/v1/registry/events
      headers:
        Authorization: [Basic YWRtaW46c3VwZXItc2VjcmV0] # 'admin:super-secret' base64 encode string
      timeout: 1s
      threshold: 5
      backoff: 3s
      ignoredmediatypes:
        - application/octet-stream
      ignore:
        mediatypes:
          - application/octet-stream
