hostname: tnas.local

ssl:
  type: static
  port: 443
  cert: /app/certs/cert.crt
  key: /app/certs/cert.key

registry:
  host: https://registry
  port: 5000
  auth_type: token
  issuer: registry_token_issuer
  service: container_registry
  certs:
    path: /app/certs
    key: /app/certs/cert.key
    public_key: /app/certs/cert.pub
    ca_root: /app/certs/cert.crt
    ip: 192.168.12.69# <- paste a real IP of docker host which publish the container
    fqdns: [registry,registry-admin,tnas.local,registry.local]

store:
  type: embed
  admin_password: "super-secret"
  embed:
    path: /app/data/store.db
