version: '2.1'
services:
  registry-admin:
    restart: unless-stopped
    image: zebox/registry-admin:master
    ports:
      - 8080:80
    environment:
      - RA_CONFIG_FILE=/app/config/basic-ra-config.yml
    volumes:
      - ./certs:/certs
      - ./config:/app/config
      - ./access:/app/access
      - ./data:/app/data

  registry:
    restart: unless-stopped
    image: registry:2
    ports:
      - 50554:5000
    volumes:
      - ./data:/var/lib/registry
      - ./certs:/certs
      - ./config/registry-config.yml:/etc/docker/registry/config.yml
      - ./access:/etc/docker/registry/access
    depends_on:
      - registry-admin