hostname: 127.0.0.1

registry:
  host: http://registry
  port: 5000
  auth_type: token
  issuer: registry_token_issuer
  service: container_registry
  certs:
    path: /app/certs
    key: /app/certs/cert.key
    public_key: /app/certs/cert.pub
    ca_root: /app/certs/cert.crt
    ip: 127.0.0.1 # <- paste a real IP of docker host which publish the container
    fqdns: [demo.host.local, localhost, registry.host.local]

store:
  type: embed
  admin_password: "super-secret"
  embed:
    path: /app/data/store.db